services:
  eyteacher-frontend-app:
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: eyteacher-frontend
    networks:
      - eyteacher-network
    restart: unless-stopped
    ports:
      - "8082:80"

networks:
  eyteacher-network:
    external: true
