services:
  eyteacher-frontend-app:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: eyteacher-frontend
    ports:
      - "8082:80"
    networks:
      - eyteacher-network
    restart: unless-stopped

networks:
  eyteacher-network:
    external: true
