sonar.projectKey=eyteacher-frontend
sonar.projectName=eyTeacher Frontend
sonar.host.url=http://localhost:9000
sonar.login=sqa_e1a7701c6123892cc9e1012dd32634a5c4d74dde

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/*.spec.ts,src/environments/**,src/main.ts,src/app/app.config.ts,src/app/app.routes.ts

sonar.javascript.lcov.reportPaths=coverage/frontend/lcov.info
sonar.typescript.tsconfigPath=tsconfig.sonar.json
