server:
  port: ${SERVER_PORT:8081}
spring:
  application:
    name: hint-api
  ai:
    ollama:
      base-url: ${SPRING_AI_OLLAMA_BASE_URL:http://localhost:11434}
      chat:
        model: qwen3.5:9b
        options:
          temperature: 0.5
jwt:
  secret: ${JWT_SECRET:[eyteacher-super-secret-key-512bits-long-enough-for-hs512-algorithm-validation]}