ALTER TABLE categories  MODIFY COLUMN description MEDIUMTEXT;
ALTER TABLE topics      MODIFY COLUMN description MEDIUMTEXT;
ALTER TABLE tasks       MODIFY COLUMN description MEDIUMTEXT NOT NULL;
ALTER TABLE solutions   MODIFY COLUMN description MEDIUMTEXT NOT NULL;
ALTER TABLE corrections MODIFY COLUMN description MEDIUMTEXT NOT NULL;
