services:
  eyteacher-ai-app:
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eyteacher-ai-app
    ports:
      - "8081:8081"
    networks:
      - eyteacher-network
    environment:
      - SERVER_PORT=8081
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - AI_MODEL=gpt-4o-mini
      - AI_TEMPERATURE=0.5
      - AI_PROVIDER=openai

networks:
  eyteacher-network:
    external: true