spring.datasource.url=jdbc:mysql://localhost:3306/eyteacherdb?connectTimeout=5000&socketTimeout=10000&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=${MYSQL_USER:eyteacher}
spring.datasource.password=${MYSQL_PASSWORD:eyteacher}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.flyway.url=jdbc:mysql://mysql:3306/eyteacherdb?connectTimeout=5000&socketTimeout=10000&allowPublicKeyRetrieval=true&useSSL=false
spring.flyway.user=${MYSQL_USER:eyteacher}
spring.flyway.password=${MYSQL_PASSWORD:eyteacher}

server.port=8081
server.ssl.enabled=false