spring.application.name=eyTeacher

# Flyway (comun)
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=${JWT_SECRET}

# Perfil por defecto para desarrollo local
spring.profiles.default=dev